name: Mirror to Aliyun
on: [workflow_dispatch]
jobs:
  mirror:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Login Aliyun
        uses: docker/login-action@v3
        with:
          registry: crpi-stnd54wvdbcabxdv.cn-huhehaote.personal.cr.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
      - name: Sync comfyui
        run: |
          docker pull mixa3607/comfyui-gfx906:v0.3.69-torch-v2.9.0-rocm-6.3.3
          docker tag mixa3607/comfyui-gfx906:v0.3.69-torch-v2.9.0-rocm-6.3.3 crpi-stnd54wvdbcabxdv.cn-huhehaote.personal.cr.aliyuncs.com/headshot/comfyui-gfx906:v0.3.69-torch-v2.9.0-rocm-6.3.3
          docker push crpi-stnd54wvdbcabxdv.cn-huhehaote.personal.cr.aliyuncs.com/headshot/comfyui-gfx906:v0.3.69-torch-v2.9.0-rocm-6.3.3
